### ISSUE TITLE
Add Simulation + SimulationCampaign to EntityCore

### ISSUE THREAD

**Issue by james-isbister** [openbraininstitute/obi-one#132]

**Comment by darshanmandge** [comment]
Realted discussion: https://github.com/openbraininstitute/prod-singlecell-simulation/issues/36

**Comment by ilkilic** [comment]
# Simulation Output Schema Proposal (LibSONATA-Compatible)

This proposal defines a standardized simulation output schema aligned with the
[LibSONATA Report Format](https://sonata-extension.readthedocs.io/en/latest/sonata_report.html). It supports both single-cell and circuit-scale simulations, enabling specific segment targeting (e.g. `soma(0.5)`) and supports all SONATA report types: **compartment**, **summation**, and **synapse**.

## Simulation Configuration (Input Schema)

We reuse the same report schema as LibSONATA with some small additions. The simulation configuration defines which variables to record, from which cells, sections, and segments (e.g. `soma(0.5)`). Each entry under the `reports` key specifies a report.

Example:

```json
"reports": {
  "soma_v": {
    "cells": "Cell0",
    "variable_name": "v",
    "type": "compartment",
    "sections": "soma",
    "compartments": "custom",
    "segment": 0.5,
    "dt": 0.1,
    "start_time": 0.0,
    "end_time": 100.0,
    "unit": "mV"
  },
  "syn_g": {
    "cells": "Cell0",
    "variable_name": "ProbAMPANMDA_EMS.g",
    "type": "synapse",
    "sections": "all",
    "dt": 0.1,
    "start_time": 0.0,
    "end_time": 100.0,
    "unit": "nS"
  },
  "cell_imem": {
    "cells": "Column",
    "variable_name": "i_membrane,IClamp",
    "type": "summation",
    "sections": "soma",
    "unit": "nA",
    "dt": 0.1,
    "start_time": 0,
    "end_time": 1000
  }
}
```

We introduce `"center"` and `"custom"` to the existing `"all"` values for `compartments`:

* `"center"`: records at 0.5
* `"all"`: records from all segments
* `"custom"`: requires a `segment` key (e.g. `0.3`)
* 
The segment field is user-facing and specifies the normalized location within a section (e.g. 0.5 for soma(0.5)). While SONATA defines element_pos for this purpose, it is not currently supported by Neurodamus or BlueCelluLab yet. 

## Output Report format: recordings.h5

Each report is stored under `/report/{population}/` with the following datasets:

```
/data                    : float32 [T, N]
/mapping/node_ids       : uint64 [C]
/mapping/index_pointers : uint64 [C + 1]
/mapping/element_ids    : uint32 [N]
/mapping/time           : float64 [3]  -> [start, end, dt]
```

Where:

* `T` = number of time steps
* `N` = number of elements (e.g., compartments, synapses)
* `C` = number of nodes (cells)

For a node `node_ids[i]`, the data for all its recorded elements is in `data[:, index_pointers[i]:index_pointers[i + 1]]`. The length of `index_pointers` is `len(node_ids) + 1`.


## Supported Report Types

The output format supports all SONATA report types:

* **Compartment report** (`type: "compartment"`): Records values from selected compartments (e.g. membrane voltage)
* **Soma report**: Special case of a compartment report targeting the soma center
* **Summation report** (`type: "summation"`): Runtime summation of one or more variables (e.g. `i_membrane`, `IClamp`)
* **Synapse report** (`type: "synapse"`): Tracks synaptic variables like conductance or weights

> ⚠️ **Each output HDF5 file must contain only one report type**. Mixing report types (e.g., compartment + synapse) in the same file is not supported by SONATA.


## Additional Metadata

This format is fully compatible with the SONATA report specification.
The only suggested addition is:

* simulation_id: a unique string stored as an HDF5 root-level attribute, for database linking.

## Spike Output Format: `spikes.h5`

If spike reporting is enabled, spikes are written to a separate file using the SONATA spike format. Each population is recorded under its own group:

```
/spikes/{population_name}/timestamps : float64 [N]
/spikes/{population_name}/node_ids   : uint64 [N]
```

* `timestamps[i]` is the time (in ms) of the `i`-th spike
* `node_ids[i]` is the cell ID (gid) that spiked at that time

This file follows the SONATA standard exactly. No additional fields are introduced. Linking to external metadata should be done using `simulation_id` or through consistent file naming.

### Enabling Spike Output

Spikes are defined in the simulation configuration following the format used by Neurodamus and BlueCelluLab:

```json
"output": {
        "output_dir": "./",
        "spikes_file": "out.h5",
        "spikes_sort_order": "by_time"
    }
```

Thank you for taking the time to read through this proposal. If anything is unclear or if you have suggestions, they’re very welcome!

also cc @darshanmandge @AurelienJaquier

**Comment by evakennyobi** [comment]
Has this commenced yet, any update? thanks

**Comment by darshanmandge** [comment]
@james-isbister has created these two related tickets:

1. https://github.com/openbraininstitute/obi-one/issues/177: 
    - @ilkilic has moved the discussion originally from the current ticket (#132) to this new ticket.
1. https://github.com/openbraininstitute/obi-one/issues/178



This ticket (#132) is meant for the schema finalisation and is different from the above.

**Comment by ilkilic** [comment]
### Draft proposal for the simulation output schema (SimulationReport)
Here is a first draft of the simulation output schema for entitycore

```yaml
SimulationReport:
  report_name: str                               # Required: report name, matching the report key in the sonata simulation config (e.g. 'dend_report_v')
  report_type: enum(                             # Required: Type of report as defined in SONATA (e.g., 'compartment', 'spike')
    'compartment', 'synapse', 'summation', 'spike', extracellular_voltage’, ‘EEG’, ‘VSD’ 
  )
  h5_file: H5File           # Required: Output HDF5 file, ideally stored in the simulation folder
```

> Reports are embedded within the `Simulation` entity as a list, rather than defined as separate entities. The current structure reflects the idea that individual reports are closely tied to the context of the simulation and are not handled independently.

```yaml
Simulation:
  name: str                                      # Required
  simulation_type: enum(                         # Required: Type of simulation
    'ion_channel', 'metabolic', 'singlecell', 'paired', 'circuit'
  )
  status: enum(                                  # Required: Simulation execution status
    'pending', 'running', 'completed', 'failed'
  )
  simulated_entity_id: int                       # Required: ID of the simulated resource
  simulation_config: SimulationConfig            # Required: Embedded configuration used for this run
  reports: Optional[List[SimulationReport]]      # Optional: simulation output reports
```

cc @darshanmandge @AurelienJaquier @MWolfR
